# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate box-packing.
#'
#' @param n number of steps to simulate
#' @param p vector of probabilities for item weights 1, ..., w
#' @useDynLib BoxPack
#' @export
pack_boxes <- function(n, p) {
    .Call('BoxPack_pack_boxes', PACKAGE = 'BoxPack', n, p)
}

