# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate box packing chain.
#'
#' @param n number of steps to simulate
#' @param p probabilities for item weights
#' @export
box_pack <- function(n, p) {
    .Call('BoxPack_box_pack', PACKAGE = 'BoxPack', n, p)
}

